name: java CI 

on:

push:
pull_request:

jobs:
build:
runs-on: ubuntu-latest

steps:
- name : checkout code 
  uses: actions/checkout@v4

- name : setup java 
  uses: actions/steupjava@v4
  with: 
  java-version: '21'
  distribution: 'temurin'

- name: check java version 
  run: java -version

- name: build and test 
  run: mvn test

- name: compile java 
  run: javac src/main.java

- name: run java
  run: java -cp src main 